### PR TITLE
Make flatten in global pool optional

### PR DESCRIPTION
**Pull request by jneeven**
For internal use

### CODE REVIEW

**Comment by jneeven** [comment]
I'm not sure what's going on with the failing tests, I don't think that's related to my changes?

**Review by lgeiger — APPROVED** [review]
Very nice!

**Comment by lgeiger** [comment]
> I'm not sure what's going on with the failing tests, I don't think that's related to my changes?

I don't think so, it looks like it only fails in TF 2.0 and 2.1 which is strange. Maybe a dependency changed?

**Comment by lgeiger** [comment]
Closing this for now, as we do not need it internally anymore.

**Pull request closed without merging**
